/**
 * batch-add.mjs — Add 350+ missing UI string translations to zh-CN.json
 * Usage: node tools/batch-add.mjs
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const DICT_PATH = join(ROOT, 'src', 'dict', 'zh-CN.json');
const dict = JSON.parse(readFileSync(DICT_PATH, 'utf-8'));
const existing = new Set(Object.keys(dict.exact));

// Comprehensive English → Chinese translations
const translations = {
  // =========== Settings Tabs & Sections ===========
  'General': '通用',
  'Appearance': '外观',
  'Editor': '编辑器',
  'Terminal': '终端',
  'Integrations': '集成',
  'Skills & MCP': '技能与 MCP',
  'Profile': '个人资料',
  'Account': '账户',
  'Global Settings': '全局设置',
  'Appearance & Theme': '外观与主题',
  'Terminal Behavior': '终端行为',
  'Editor Preferences': '编辑器偏好',
  'Keyboard Shortcuts': '键盘快捷键',
  'App Settings': '应用设置',
  'Project settings': '项目设置',

  // =========== Theme/Font/Layout ===========
  'Theme': '主题',
  'Font': '字体',
  'Zoom': '缩放',
  'Layout': '布局',
  'Density': '密度',
  'System': '系统',
  'Light': '浅色',
  'Dark': '深色',
  'Compact': '紧凑',
  'Comfortable': '舒适',
  'Custom': '自定义',

  // =========== Profiles ===========
  'Profiles': '配置文件',
  'Create Profile': '创建配置文件',
  'Delete Profile': '删除配置文件',
  'Profile Name': '配置文件名称',
  'Base Profile': '基础配置文件',

  // =========== Account ===========
  'Sign Out': '退出登录',
  'Manage Account': '管理账户',
  'Subscription': '订阅',
  'Usage': '使用量',
  'Billing': '计费',

  // =========== Sidebar ===========
  'Pinned': '已固定',
  'Sort projects': '项目排序',
  'Sort by': '排序方式',
  'Created at': '创建时间',
  'Last used': '最近使用',
  'Add Project': '添加项目',
  'Drop to add project': '拖放以添加项目',
  'Creating repository...': '正在创建仓库...',
  'Cloning...': '正在克隆...',
  'Registering...': '正在注册...',
  'Collapse': '折叠',
  'Expand': '展开',
  'Open project': '打开项目',
  'Project not found at path': '在路径中未找到项目',
  'New task for': '新建任务',
  'Change SSH Connection': '更改 SSH 连接',
  'Remove Project': '移除项目',
  'Toggle left sidebar': '切换左侧边栏',
  'Creating task workspace...': '正在创建任务工作区...',
  'Update': '更新',
  'Cannot add project': '无法添加项目',
  'Drop a folder to add it as a project.': '拖放文件夹以将其添加为项目。',
  'is not a git repository.': '不是 git 仓库。',
  'Failed to add': '添加失败',
  'as a project.': '作为项目。',
  'Projects added': '项目已添加',
  'projects added.': '个项目已添加。',
  'Library': '库',

  // =========== Task Settings ===========
  'Task Settings': '任务设置',
  'Branch Settings': '分支设置',
  'Worktree Settings': '工作树设置',
  'Lifecycle Scripts': '生命周期脚本',

  // =========== SSH ===========
  'SSH Connections': 'SSH 连接',
  'Add Connection': '添加连接',
  'Edit Connection': '编辑连接',
  'Delete Connection': '删除连接',

  // =========== Git/Repository ===========
  'GitHub Accounts': 'GitHub 账户',
  'Add a GitHub account': '添加 GitHub 账户',
  'Default branch': '默认分支',
  'Base remote': '基础远程',
  'Push remote': '推送远程',
  'Repository Settings': '仓库设置',
  'Worktree directory': '工作树目录',
  'Detached HEAD': '分离的 HEAD',
  'Create an initial commit first': '请先创建初始提交',
  'Cannot publish: HEAD is detached': '无法发布: HEAD 处于分离状态',
  'Publish branch': '发布分支',
  'Create or link a remote, then publish this branch': '创建或链接远程仓库，然后发布此分支',

  // =========== MCP/Skills ===========
  'MCP Servers': 'MCP 服务器',
  'Add MCP Server': '添加 MCP 服务器',
  'Skills Directory': '技能目录',

  // =========== Projects/Tasks ===========
  'Active': '活跃',
  'Archived': '已归档',
  'Create Task': '创建任务',
  'Task name': '任务名称',
  'Task name...': '任务名称...',
  'Select a project': '选择项目',
  'Search projects...': '搜索项目...',
  'Search tasks...': '搜索任务...',
  'No tasks': '无任务',
  'No tasks found': '未找到任务',
  'Clear selection': '清除选择',
  'Project Name': '项目名称',
  'Project Directory': '项目目录',
  'Remote Directory': '远程目录',
  'Repository URL': '仓库 URL',
  'Enter a project name': '输入项目名称',
  'Enter a repository name': '输入仓库名称',
  'Enter a repository URL': '输入仓库 URL',
  'Select a project directory to open': '选择要打开的项目目录',
  'This directory is not a git repository.': '此目录不是 git 仓库。',
  'Initialize git repository': '初始化 git 仓库',
  'Task names only allow letters, numbers, and hyphens.': '任务名称仅允许字母、数字和连字符。',

  // =========== Task Context Menu ===========
  'Unpin task': '取消固定任务',
  'Pin task': '固定任务',
  'Convert to regular task': '转换为常规任务',
  'Archive': '归档',
  'Restore': '恢复',
  'Copy branch name': '复制分支名称',
  'Branch name copied': '分支名称已复制',
  'The branch name could not be copied to the clipboard.': '分支名称无法复制到剪贴板。',

  // =========== Delete Task ===========
  'Delete task': '删除任务',
  'will be permanently deleted. This action cannot be undone.': '将被永久删除。此操作无法撤消。',

  // =========== Git Changes ===========
  'Commit message': '提交信息',
  'Description': '描述',
  'Committing...': '正在提交...',
  'Opening PR...': '正在打开 PR...',
  'Committed': '已提交',
  'Pushing...': '正在推送...',
  'Pushed': '已推送',
  'Fetch changes': '获取更改',
  'Fetching...': '正在获取...',
  'Pull changes': '拉取更改',
  'Pulling...': '正在拉取...',
  'Nothing to pull': '没有可拉取的内容',
  'Push changes': '推送更改',
  'Nothing to push': '没有可推送的内容',
  'Publish': '发布',
  'Publishing...': '正在发布...',
  'Add Remote': '添加远程',
  'Changed': '已更改',
  'Nothing staged': '未暂存',
  'Working tree clean': '工作树干净',
  'Discard all': '全部放弃',
  'Stage': '暂存',
  'Stage all': '全部暂存',
  'Unstage': '取消暂存',
  'Unstage all': '全部取消暂存',
  'Unstage selected files': '取消暂存选中的文件',
  'Unstage all files': '取消暂存所有文件',
  'Discard Files Changes': '放弃文件更改',
  'Discard All Changes': '放弃所有更改',
  'Are you sure you want to discard the changes to the selected files? This can not be undone.': '确定要放弃对所选文件的更改吗？此操作无法撤消。',
  'Are you sure you want to discard all changes? This can not be undone.': '确定要放弃所有更改吗？此操作无法撤消。',
  'Nothing staged -- Stage files above to include them in a commit.': '未暂存 -- 暂存上方文件以将其包含在提交中。',
  'Working tree clean -- No uncommitted file changes.': '工作树干净 -- 没有未提交的文件更改。',

  // =========== PR ===========
  'Pull Requests': '拉取请求',
  'Create draft PR': '创建草稿 PR',
  'Create Draft PR': '创建草稿 PR',
  'Head Branch': '源分支',
  'Target': '目标',
  'Base Branch': '基础分支',
  'PR title': 'PR 标题',
  'Select a base branch': '选择基础分支',
  'Files': '文件',
  'Commits': '提交',
  'Checks': '检查',
  'Merge pull request': '合并拉取请求',
  'Squash and merge': '压缩并合并',
  'Rebase and merge': '变基并合并',
  'Skip push and open a PR from the current remote state': '跳过推送，从当前远程状态打开 PR',
  'Force full sync': '强制完全同步',
  'Full sync': '完全同步',
  'Incremental sync': '增量同步',
  'Single PR': '单个 PR',
  'Sync failed': '同步失败',
  'Unknown error': '未知错误',
  'Sync complete': '同步完成',
  'Syncing PRs...': '正在同步 PR...',
  'Sync cancelled': '同步已取消',
  'Draft pull request': '草稿拉取请求',
  'Merge status unknown': '合并状态未知',
  'Ready to merge': '可以合并',
  'Merge conflicts': '合并冲突',
  'Branch is out-of-date': '分支已过期',
  'Merging is blocked': '合并被阻止',
  'Checks still running': '检查仍在运行',
  'Checks not passing': '检查未通过',
  'Checks pending or not passing': '检查待处理或未通过',
  'No conflicts or required reviews.': '没有冲突或必需的审查。',
  'Mark ready for review to enable merging.': '标记为可审查以启用合并。',
  'Resolve conflicts before merging.': '合并前解决冲突。',
  'Update the branch...': '更新分支...',
  'Required reviews, checks, or branch rules...': '需要审查、检查或分支规则...',
  'A pull request is already open': '已有打开的拉取请求',
  'Create a pull request': '创建拉取请求',
  'Refresh pull requests': '刷新拉取请求',
  'Pull requests unavailable': '拉取请求不可用',
  'Could not load pull requests': '无法加载拉取请求',
  'No pull requests': '没有拉取请求',
  'Push your branch and create a PR to start a review.': '推送分支并创建 PR 以开始审查。',
  'Bypass rules and merge': '绕过规则并合并',
  'Mark ready': '标记为就绪',
  'Marking ready...': '正在标记为就绪...',
  'Merging...': '正在合并...',
  'Merge without waiting': '无需等待即可合并',

  // =========== Changes View ===========
  'Switch to tree view': '切换到树视图',
  'Switch to flat list': '切换到平铺列表',
  'No changes -- Select or make changes to files to see diffs.': '没有更改 -- 选择或修改文件以查看差异。',
  'Binary file': '二进制文件',
  'Binary file -- no diff available': '二进制文件 -- 没有可显示的差异',
  'Preview unavailable': '预览不可用',
  'Preview unavailable on SSH workspaces': 'SSH 工作区上预览不可用',
  'Preview unavailable for this format': '此格式的预览不可用',
  'Preview unavailable -- file is too large': '预览不可用 -- 文件太大',
  'Preview unavailable -- Git LFS smudge filter not applied': '预览不可用 -- Git LFS 滤镜未应用',
  'Failed to load image': '加载图片失败',
  'File added': '文件已添加',
  'File deleted': '文件已删除',
  'Failed to decode image': '解码图片失败',
  'Original': '原始',
  'Modified': '修改后',
  'No changes': '没有更改',

  // =========== Commit/PR Comments ===========
  'Add comment': '添加评论',
  'Edit comment': '编辑评论',
  'Cancel (Esc)': '取消 (Esc)',
  'Cancel comment': '取消评论',
  'Submit': '提交',
  'Submit comment': '提交评论',
  'Save comment': '保存评论',
  'Delete comment': '删除评论',
  'Update the note...': '更新备注...',

  // =========== Conversations ===========
  'Conversations': '对话',
  'Create Conversation': '创建对话',
  'Delete conversation': '删除对话',
  'Agent': '智能体',
  'Auto-approve permissions': '自动批准权限',
  'Create': '创建',
  'Creating...': '正在创建...',
  'Auto approve': '自动批准',
  'Add a prompt to the initial message': '将提示词添加到初始消息',
  'Add an optional initial message...': '添加可选的初始消息...',
  'Prompt unavailable': '提示词不可用',
  'Prompts': '提示词',
  'Initial Conversation': '初始对话',
  'Workspace Settings': '工作区设置',
  'Based on': '基于',
  'Issue': '议题',
  'Pull Request': '拉取请求',

  // =========== Agent Status ===========
  'Agent is working': '智能体正在工作',
  'Agent is awaiting input': '智能体等待输入',
  'Agent error': '智能体错误',
  'Agent completed': '智能体已完成',

  // =========== Context Bar ===========
  'Add context': '添加上下文',
  'No context found': '未找到上下文',
  'Add to input': '添加到输入',
  'Hide context bar': '隐藏上下文栏',
  'Adding issue context...': '正在添加议题上下文...',
  'Add issue context to the initial message': '将议题上下文添加到初始消息',

  // =========== Add Remote ===========
  'Add Remote': '添加远程',
  'Create Repository': '创建仓库',
  'Link Existing': '关联现有',
  'Create & Publish': '创建并发布',
  'Link & Publish': '关联并发布',
  'Adding...': '正在添加...',
  'Owner': '所有者',
  'Visibility': '可见性',
  'Private': '私有',
  'Public': '公开',
  'Remote URL': '远程 URL',

  // =========== Comments ===========
  'Loading comments...': '正在加载评论...',
  'Unable to load comments': '无法加载评论',
  'No comments available': '没有评论',
  'Resolved': '已解决',
  'Unknown author': '未知作者',

  // =========== Loading/State ===========
  'Load more': '加载更多',
  'Loading more...': '正在加载更多...',
  'Loading files...': '正在加载文件...',
  'Unable to load files': '无法加载文件',
  'No file changes': '没有文件更改',
  'No commits': '没有提交',
  'No checks available': '没有可用的检查',
  'No checks or comments': '没有检查或评论',

  // =========== Projects ===========
  'Setting up project...': '正在设置项目...',
  'Failed to set up project': '设置项目失败',
  'SSH not connected': 'SSH 未连接',
  'Project not found': '未找到项目',
  'Share with team': '与团队共享',
  'Saving...': '正在保存...',
  'Saved': '已保存',
  'Save settings': '保存设置',
  'Detected external project config.': '检测到外部项目配置。',
  'Import into Emdash': '导入到 Emdash',
  'Select a directory': '选择目录',
  'Use this directory': '使用此目录',
  'Empty directory': '空目录',
  'Failed to list directory': '列出目录失败',
  'Select an SSH connection to browse remote directories.': '选择 SSH 连接以浏览远程目录。',
  'Select or add a connection': '选择或添加连接',
  'Choose': '选择',
  'Browse': '浏览',
  'Back': '返回',
  'Forward': '前进',
  'Up one directory': '上一级目录',
  'Local': '本地',
  'SSH': 'SSH',
  'GitHub CLI': 'GitHub CLI',
  'OAuth': 'OAuth',
  'Device flow': '设备流程',
  'Saved token': '已保存的令牌',
  'Open': '打开',
  'Closed': '已关闭',
  'Search by title, branch, or number...': '按标题、分支或编号搜索...',
  'Sort...': '排序...',
  'Filter by': '筛选方式',
  'Author': '作者',
  'Label': '标签',
  'Assignee': '指派人',
  'Newest': '最新',
  'Oldest': '最早',
  'Recently Updated': '最近更新',
  'Open PR on GitHub': '在 GitHub 上打开 PR',
  'Review in Task': '在任务中审查',
  'Pull requests are currently available only for configured GitHub remotes.': '拉取请求目前仅适用于已配置的 GitHub 远程仓库。',
  'Delete project': '删除项目',
  'will be deleted. The project folder and worktrees will stay on the filesystem.': '将被删除。项目文件夹和工作树将保留在文件系统中。',
  'Dismiss': '忽略',

  // =========== Settings Descriptions ===========
  'Add the selected issue to the initial agent prompt when creating a task from an issue.': '从议题创建任务时，将所选议题添加到初始智能体提示词中。',
  'Used for pull requests and issues in this project.': '用于此项目中的拉取请求和议题。',
  'Change where worktrees are created.': '更改工作树的创建位置。',
  'The branch new tasks are created from by default.': '默认情况下创建新任务的来源分支。',
  'Used for fetching remote branches': '用于获取远程分支',
  'Used when publishing task branches and pushing commits.': '在发布任务分支和推送提交时使用。',
  'Run the agent session inside a tmux session.': '在 tmux 会话中运行智能体会话。',
  'Unavailable GitHub account': '不可用的 GitHub 账户',
  'No longer connected': '不再连接',
  'No GitHub account': '没有 GitHub 账户',
  'Same as base remote': '与基础远程相同',
  'Lifecycle scripts': '生命周期脚本',
  'Shell commands run at each stage of the worktree lifecycle': '在工作树生命周期的每个阶段运行的 Shell 命令',
  'Auto-run on task creation': '创建任务时自动运行',
  'for the full project config reference.': '查看完整的项目配置参考。',
  'Preserve patterns': '保留模式',
  'Shell setup': 'Shell 设置',
  'Setup script': '设置脚本',
  'Run script': '运行脚本',
  'Teardown script': '清理脚本',
  'Commands used to provision and terminate BYOI infrastructure for tasks.': '用于为任务配置和终止 BYOI 基础设施的命令。',
  'Share settings with your team': '与团队共享设置',
  'This writes the selected settings to .emdash.json': '将所选设置写入 .emdash.json',
  'Write to': '写入到',
  'Settings to share': '要共享的设置',
  'Writing...': '正在写入...',
  'Wrote .emdash.json': '已写入 .emdash.json',
  'Write .emdash.json': '写入 .emdash.json',
  'Overriding': '覆盖中',
  'Use team settings': '使用团队设置',
  'Use team settings for': '使用团队设置',
  'Reset changes': '重置更改',

  // =========== Project Config Import ===========
  'Import project config': '导入项目配置',
  'Settings to import': '要导入的设置',
  'Save to': '保存到',
  'Importing...': '正在导入...',
  'Imported': '已导入',
  'Import': '导入',
  'Select config': '选择配置',
  'Failed to import project config.': '导入项目配置失败。',
  '.emdash.json -- commit to share with team': '.emdash.json -- 提交以与团队共享',
  'Settings -- local to this machine': '设置 -- 仅本机',

  // =========== Context Fields ===========
  'Provider:': '提供商:',
  'Identifier:': '标识符:',
  'URL:': 'URL:',
  'Project:': '项目:',

  // =========== Task List ===========
  'Create a Task from a Branch': '从分支创建任务',
  'Create from Issue': '从议题创建',
  'Create from Pull Request': '从拉取请求创建',
  'Create a task from an existing branch': '从现有分支创建任务',
  'Link and create a task from an issue': '从议题关联并创建任务',
  'Create a task from a pull request': '从拉取请求创建任务',
  'No remote repository connected': '未连接远程仓库',
  'Configure issue integrations': '配置议题集成',

  // =========== Misc ===========
  'An error occurred': '发生错误',
  'SSH channel unavailable': 'SSH 通道不可用',
  'Add a connection to create and manage remote projects.': '添加连接以创建和管理远程项目。',
  'Advanced settings': '高级设置',
  'Additional parameters': '额外参数',
  'Add variable': '添加变量',
  'Agent Settings': '智能体设置',
  'Agents': '智能体',
  'All': '全部',
  'Available': '可用',
  'Installed': '已安装',
  'Install': '安装',
  'Uninstall': '卸载',
  'Configure': '配置',
  'Update Available': '有可用更新',
  'Running': '运行中',
  'Stopped': '已停止',
  'Version': '版本',
  'Enabled': '已启用',
  'Disabled': '已禁用',
  'Default': '默认',

  // =========== General Settings ===========
  'Language': '语言',
  'Region': '区域',
  'Cache': '缓存',
  'Clear Cache': '清除缓存',
  'Logs': '日志',
  'Open Logs Folder': '打开日志文件夹',
  'Telemetry': '遥测',
  'Usage Data': '使用数据',
  'Send anonymous usage data': '发送匿名使用数据',
  'Updates': '更新',
  'Check for Updates': '检查更新',
  'Auto-update': '自动更新',
  'Current Version': '当前版本',
  'Release Notes': '发行说明',
  'Experimental': '实验性',
  'Experimental Features': '实验性功能',
  'Privacy Policy': '隐私政策',
  'Terms of Service': '服务条款',
  'Learn more': '了解更多',
  'Get started': '开始使用',
  'Documentation': '文档',
  'Report Issue': '报告问题',
  'Copy Installation ID': '复制安装 ID',
  'Troubleshooting': '故障排除',
  'Copy failed': '复制失败',
  'Repository Name': '仓库名称',

  // =========== Footer/Status info ===========
  'Nothing to pull.': '没有可拉取的内容。',
  'Nothing to push.': '没有可推送的内容。',
};

// Add missing translations
let added = 0;
let skipped = 0;
for (const [en, zh] of Object.entries(translations)) {
  if (existing.has(en)) {
    skipped++;
  } else {
    dict.exact[en] = zh;
    existing.add(en);
    added++;
  }
}

// Sort keys alphabetically for maintainability
const sorted = {};
Object.keys(dict.exact).sort().forEach(k => {
  sorted[k] = dict.exact[k];
});
dict.exact = sorted;

// Write back
writeFileSync(DICT_PATH, JSON.stringify(dict, null, 2) + '\n', 'utf-8');

console.log(`Added ${added} translations, skipped ${skipped} (already in dict).`);
console.log(`Total exact entries: ${Object.keys(dict.exact).length}`);
