/**
 * merge-dict.mjs — Merge newly extracted UI strings into zh-CN.json with translations.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const DICT_PATH = join(ROOT, 'src', 'dict', 'zh-CN.json');

const dict = JSON.parse(readFileSync(DICT_PATH, 'utf-8'));
const existing = new Set(Object.keys(dict.exact));

// All new translations extracted from source code
const newTranslations = {
  // === Command palette / Commands ===
  "Open application settings": "打开应用设置",
  "Open the Library": "打开库",
  "Add a new local or SSH project": "添加新的本地或 SSH 项目",
  "Create a new task in this project": "在此项目中创建新任务",
  "Send feedback to the emdash team": "向 Emdash 团队发送反馈",
  "Switch between light and dark themes": "在浅色和深色主题间切换",
  "Navigate to the previous location": "导航到上一个位置",
  "Navigate to the next location": "导航到下一个位置",
  "Create a new conversation in the current task": "在当前任务中创建新对话",
  "Create a new conversation in a split pane to the right": "在右侧分屏中创建新对话",
  "Open the Changes panel in the right sidebar": "打开右侧边栏的更改面板",
  "Open the Conversations panel in the right sidebar": "打开右侧边栏的对话面板",
  "Open the Files panel in the right sidebar": "打开右侧边栏的文件面板",
  "Open the terminal drawer": "打开终端抽屉",
  "Show or hide the terminal drawer": "显示或隐藏终端抽屉",
  "Show or hide the right sidebar": "显示或隐藏右侧边栏",
  "Show or hide the left sidebar": "显示或隐藏左侧边栏",
  "Create a new terminal session": "创建新终端会话",
  "Open an in-app browser for this task": "为此任务打开应用内浏览器",
  "Go back in the active browser tab": "在浏览器标签中后退",
  "Go forward in the active browser tab": "在浏览器标签中前进",
  "Reload the active browser tab": "重新加载浏览器标签",
  "Focus the URL field in the active browser tab": "聚焦浏览器地址栏",
  "Open the active browser URL in the system browser": "在系统浏览器中打开当前页面",
  "Copy the active browser URL": "复制当前浏览器地址",
  "Fetch latest changes from remote": "从远程获取最新更改",
  "Pull latest changes from remote": "从远程拉取最新更改",
  "Push commits to remote": "推送提交到远程",
  "Pin this task to keep it at the top": "置顶此任务",
  "Detach this task from its automation run": "从自动化运行中分离此任务",
  "Switch to the next task": "切换到下一个任务",
  "Switch to the previous task": "切换到上一个任务",
  "Open the command palette to quickly search and navigate": "打开命令面板以快速搜索和导航",
  "Delete the selected tasks": "删除选中的任务",
  "Create a new project": "创建新项目",
  "Create a new task": "创建新任务",
  "Close the current modal or dialog": "关闭当前模态框或对话框",
  "Confirm the current dialog action": "确认当前对话框操作",
  "Move the active tab to a new pane on the right": "将当前标签移动到右侧新窗格",
  "Open the project in the default editor": "在默认编辑器中打开项目",
  "Copy the current in-app browser URL": "复制当前应用内浏览器地址",
  "Close the active tab": "关闭当前标签",
  "Switch to the next tab": "切换到下一个标签",
  "Switch to the previous tab": "切换到上一个标签",
  "Send feedback to the emdash team": "向 Emdash 团队发送反馈",

  // === Menu ===
  "Settings…": "设置…",
  "Check for Updates…": "检查更新…",
  "Report Issue…": "报告问题…",
  "File": "文件",
  "Edit": "编辑",
  "View": "查看",
  "Help": "帮助",
  "Quit": "退出",
  "Undo": "撤销",
  "Redo": "重做",
  "Docs": "文档",
  "Changelog": "更新日志",
  "Troubleshooting": "故障排除",
  "Copy Installation ID": "复制安装 ID",
  "Give Feedback": "发送反馈",
  "Close Tab": "关闭标签",
  "Toggle Left Sidebar": "切换左侧边栏",
  "Toggle Right Sidebar": "切换右侧边栏",
  "Toggle Terminal Drawer": "切换终端抽屉",
  "Toggle Theme": "切换主题",
  "Go Back": "后退",
  "Go Forward": "前进",
  "Open Settings": "打开设置",
  "Open Library": "打开库",
  "New Project": "新建项目",
  "New Task": "新建任务",
  "New Conversation": "新建对话",
  "New Conversation in Right Split": "在右侧分屏新建对话",
  "New Terminal": "新建终端",
  "Open Browser": "打开浏览器",
  "Copy Browser URL": "复制浏览器地址",
  "View Changes": "查看更改",
  "View Conversations": "查看对话",
  "View Files": "查看文件",
  "View Terminals": "查看终端",
  "Next Tab": "下一个标签",
  "Previous Tab": "上一个标签",
  "Next Task": "下一个任务",
  "Previous Task": "上一个任务",
  "Git Fetch": "Git 获取",
  "Git Pull": "Git 拉取",
  "Git Push": "Git 推送",
  "Split Pane": "分屏",
  "Close Modal": "关闭模态框",
  "Browser Back": "浏览器后退",
  "Browser Forward": "浏览器前进",
  "Reload Browser": "重新加载浏览器",
  "Focus Browser URL": "聚焦浏览器地址",
  "Open Browser URL Externally": "在外部浏览器打开",
  "Pin Task": "置顶任务",
  "Convert to Regular Task": "转换为普通任务",
  "Reload": "重新加载",
  "Resource Monitor": "资源监控",
  "Show CPU and memory performance for running agents": "显示运行中 Agent 的 CPU 和内存性能",

  // === Command groups ===
  "App": "应用",
  "Navigation": "导航",
  "Task View": "任务视图",
  "Tab Navigation": "标签导航",
  "Panel": "面板",
  "Browser": "浏览器",
  "Terminals": "终端",
  "Git": "Git",
  "Task": "任务",
  "Conversations": "对话",

  // === UI elements ===
  "Back": "返回",
  "Select": "选择",
  "Navigate": "导航",
  "Search tasks, projects, actions…": "搜索任务、项目、操作…",
  "No results for &ldquo;{query}&rdquo;": "没有找到 \"{query}\" 的结果",
  "Suggested Actions": "建议操作",
  "Recent Tasks": "最近任务",
  "Recent Conversations": "最近对话",
  "Enter": "确认",
  "Escape": "退出",
  "ArrowUp": "上箭头",
  "ArrowDown": "下箭头",
  "Backspace": "退格",

  // === Home / Welcome ===
  "Start shipping": "开始使用",
  "Welcome.": "欢迎。",
  "Open a local project": "打开本地项目",
  "Create a project by creating a new repository on GitHub": "在 GitHub 上创建新仓库来建立项目",
  "Clone a GitHub repository to work on locally": "克隆 GitHub 仓库到本地",
  "Create a project on a remote SSH server": "在远程 SSH 服务器上创建项目",
  "New Project": "新建项目",
  "Clone from GitHub": "从 GitHub 克隆",
  "Add remote project": "添加远程项目",

  // === Settings ===
  "General": "通用",
  "Appearance": "外观",
  "Theme": "主题",
  "Editor": "编辑器",
  "Terminal": "终端",
  "SSH": "SSH",
  "Integrations": "集成",
  "Accounts": "账户",
  "Skills": "技能",
  "MCP": "MCP",
  "Prompts": "提示词",
  "Automations": "自动化",
  "Workspace": "工作区",
  "About": "关于",
  "Connected to GitHub": "已连接 GitHub",

  // === Tasks ===
  "In Progress": "进行中",
  "Done": "已完成",
  "Changes": "更改",
  "Files": "文件",
  "Active Tasks": "活跃任务",
  "Completed Tasks": "已完成任务",
  "Task List": "任务列表",
  "Delete Task": "删除任务",
  "Rename Task": "重命名任务",
  "Create Task": "创建任务",

  // === Git ===
  "Commit": "提交",
  "Push": "推送",
  "Pull": "拉取",
  "Fetch": "获取",
  "Branch": "分支",
  "Merge": "合并",
  "Changes": "更改",
  "Staged": "已暂存",
  "Unstaged": "未暂存",
  "Diff": "差异",
  "Commit Message": "提交信息",
  "Create Branch": "创建分支",
  "Switch Branch": "切换分支",
  "Delete Branch": "删除分支",
  "Create PR": "创建 PR",
  "Pull Request": "拉取请求",

  // === Misc ===
  "Copy": "复制",
  "Copy Image URL": "复制图片地址",
  "Copy Link": "复制链接",
  "Open Image": "打开图片",
  "Open Image in New Tab": "在新标签打开图片",
  "Open Link": "打开链接",
  "Open Link in New Tab": "在新标签打开链接",
  "Close": "关闭",
  "Delete": "删除",
  "Save": "保存",
  "Cancel": "取消",
  "Confirm": "确认",
  "Retry": "重试",
  "Discard": "放弃",
  "Add": "添加",
  "Remove": "移除",
  "Edit": "编辑",
  "Rename": "重命名",
  "Import": "导入",
  "Export": "导出",
  "Refresh": "刷新",
  "Search": "搜索",
  "Filter": "筛选",
  "Sort": "排序",
  "Clear": "清除",
  "Enable": "启用",
  "Disable": "禁用",
  "Setup": "设置",
  "Install": "安装",
  "Uninstall": "卸载",
  "Sign In": "登录",
  "Sign Out": "退出登录",
  "Connect": "连接",
  "Disconnect": "断开连接",
  "Connections": "连接",

  // === Status messages ===
  "Loading...": "加载中...",
  "Saving...": "保存中...",
  "Deleting...": "删除中...",
  "Thinking...": "思考中...",
  "Running...": "运行中...",
  "Setting up workspace…": "设置工作区中…",
  "Preparing task…": "准备任务中…",
  "Signing in…": "登录中…",
  "Creating repository…": "创建仓库中…",
  "Creating task…": "创建任务中…",
  "Checking…": "检查中…",
  "Importing...": "导入中...",
  "Adding...": "添加中...",
  "Search agents…": "搜索智能体…",
  "Search tasks…": "搜索任务…",
  "Search labels…": "搜索标签…",
  "Choose file…": "选择文件…",
  "Syncing PRs…": "同步 PR 中…",
  "Connecting to": "正在连接到",

  // === Error / Status ===
  "Something went wrong": "出了点问题",
  "An unexpected error occurred": "发生了意外错误",
  "Please try again": "请重试",
  "Could not connect": "无法连接",
  "Connection lost": "连接断开",
  "Authentication failed": "认证失败",
  "Permission denied": "权限不足",
  "Copied to clipboard": "已复制到剪贴板",
  "Changes saved": "更改已保存",
  "Changes discarded": "更改已放弃",
  "not found": "未找到",
  "No results": "无结果",
  "No data": "无数据",
  "Copy failed": "复制失败",
  "Import failed": "导入失败",
  "Failed to load": "加载失败",

  // === Project ===
  "Create Project": "创建项目",
  "Open project": "打开项目",
  "Create repository": "创建仓库",
  "Add remote project": "添加远程项目",
  "Repository": "仓库",
  "Empty": "空",

  // === Misc phrases ===
  "Are you sure?": "确定吗？",
  "Are you sure you want to discard all changes? This can not be undone.": "确定要放弃所有更改吗？此操作不可撤销。",
  "Learn more": "了解更多",
  "Get started": "开始使用",
  "Show more": "显示更多",
  "Show less": "收起",
  "View all": "查看全部",
  "Select all": "全选",
  "Deselect all": "取消全选",
  "Command Palette": "命令面板",
  "Search files, actions, agents...": "搜索文件、操作、智能体...",
  "Toggle Sidebar": "切换侧边栏",
  "Left Sidebar": "左侧边栏",
  "Right Sidebar": "右侧边栏",
  "Collapse All": "全部折叠",
  "Expand All": "全部展开",
  "Search files": "搜索文件",
  "Keyboard Shortcuts": "键盘快捷键",
  "Keybindings": "快捷键",
  "Font Size": "字体大小",
  "Font Family": "字体",
  "Tab Size": "Tab 大小",
  "Word Wrap": "自动换行",
  "Line Numbers": "行号",
  "Minimap": "小地图",
  "Auto Save": "自动保存",
  "Format on Save": "保存时格式化",
  "Color Theme": "颜色主题",
  "Light": "浅色",
  "Dark": "深色",
  "System": "系统",
  "Providers": "提供商",
  "Agent": "智能体",
  "Agents": "智能体",
  "Add Provider": "添加提供商",
  "Auto-approve": "自动批准",
  "Select a provider": "选择提供商",
  "Model": "模型",
  "Models": "模型",
  "Default Model": "默认模型",
  "Preferences": "偏好设置",
  "Account": "账户",
  "Profile": "个人资料",
  "Notifications": "通知",
  "Language": "语言",
  "Version": "版本",
  "Feedback": "反馈",
  "Send Feedback": "发送反馈",
  "Documentation": "文档",
  "Community": "社区",
  "Check for Updates": "检查更新",
  "Update Available": "有可用更新",
  "Restart to Update": "重启以更新",
  "Sign in failed": "登录失败",
  "Thanks for your feedback!": "感谢您的反馈！",
  "Delete project": "删除项目",
  "Delete conversation": "删除对话",
  "Delete automation": "删除自动化",
  "Delete prompt?": "删除提示词？",
  "Are you sure you want to discard the changes to the selected files? This can not be undone.": "确定要放弃所选文件的更改吗？此操作不可撤销。",
  "Discard All Changes": "放弃所有更改",
  "Discard Files Changes": "放弃文件更改",
  "Commit & Push": "提交并推送",
  "Commit & Create PR": "提交并创建 PR",
  "Clear browser storage?": "清除浏览器存储？",
  "This clears cookies, local storage, IndexedDB, and cache for this browser session only.": "仅清除此浏览器会话的 Cookie、本地存储、IndexedDB 和缓存。",
  "Add Connection": "添加连接",
  "Delete Connection": "删除连接",
  "Edit Connection": "编辑连接",
  "Failed to delete SSH connection": "删除 SSH 连接失败",
  "New conversation": "新对话",
  "Initial Conversation": "初始对话",
  "Workspace Settings": "工作区设置",
  "Project repository": "项目仓库",
  "Review prompt": "审查提示词",
  "Feedback sent": "反馈已发送",
  "Theme not changed": "主题未更改",
  "Shortcut conflict": "快捷键冲突",
  "Shortcut removed": "快捷键已移除",
  "Shortcut reset": "快捷键已重置",
  "Shortcut updated": "快捷键已更新",
  "Automation created": "自动化已创建",
  "Skill installed": "技能已安装",
  "Skill removed": "技能已移除",
  "Skill has been uninstalled": "技能已卸载",
  "Prompt deleted": "提示词已删除",
  "Integration connected": "集成已连接",
  "Integration set up successfully.": "集成设置成功。",
  "Failed to send feedback": "发送反馈失败",
  "Failed to check project": "检查项目失败",
  "Failed to refresh pull requests": "刷新拉取请求失败",
  "Cannot add project": "无法添加项目",
  "Cannot delete SSH connection": "无法删除 SSH 连接",
  "IPC failed": "IPC 失败",
  "Please copy the code manually": "请手动复制代码",
  "Drop a folder to add it as a project.": "拖放文件夹以添加为项目。",
  "Checks not passing": "检查未通过",
  "Checks pending or not passing": "检查等待或未通过",
  "Checks still running": "检查仍在运行",
  "Checks passing, but PR is unstable": "检查通过，但 PR 不稳定",
  "Ready to merge": "可以合并",
  "Merge conflicts": "合并冲突",
  "Merge status unknown": "合并状态未知",
  "Merging is blocked": "合并被阻止",
  "Branch is out-of-date": "分支已过期",
  "Refresh PR status and try again.": "刷新 PR 状态并重试。",
  "Failed to mark pull request ready": "标记 PR 为就绪失败",
  "Pull request sync was cancelled.": "拉取请求同步已取消。",
  "GitHub API is disabled for this project.": "此项目已禁用 GitHub API。",
  "No GitHub account is configured for this project.": "此项目未配置 GitHub 账户。",
  "Unable to resolve GitHub account for project: git config failed": "无法解析项目的 GitHub 账户：git 配置失败",
  "Connect GitHub from account settings.": "在账户设置中连接 GitHub。",
  "Unable to load GitHub data": "无法加载 GitHub 数据",
  "auth required": "需要认证",
  "Failed to refresh MCP data": "刷新 MCP 数据失败",
  "Failed to save server": "保存服务器失败",
  "Failed to remove server": "移除服务器失败",
  "Remove MCP server?": "移除 MCP 服务器？",
  "Could not clear browser data": "无法清除浏览器数据",
  "Could not capture screenshot": "无法截屏",
  "Could not copy browser URL": "无法复制浏览器地址",
  "Browser URL copied": "浏览器地址已复制",
  "File copied": "文件已复制",
  "Path copied": "路径已复制",
  "Branch name copied": "分支名称已复制",
  "Screenshot copied to clipboard": "截图已复制到剪贴板",
  "Relative path copied": "相对路径已复制",
  "Try again, or reload the browser view manually.": "重试，或手动重新加载浏览器视图。",
  "Quit Emdash?": "退出 Emdash？",
  "Active terminal sessions and running agents will stop when the app quits.": "退出应用后，活跃终端会话和运行中的 Agent 将停止。",
  "Close tab?": "关闭标签？",
  "Delete SSH connection": "删除 SSH 连接",
  "This SSH connection is still used by at least one project. Change those projects to another connection before deleting it.": "此 SSH 连接仍被至少一个项目使用。删除前请将这些项目切换到其他连接。",
  "Failed to load SSH connection usage": "加载 SSH 连接使用情况失败",
  "Delete Selected Tasks": "删除选中任务",
  "Sign in failed": "登录失败",
  "Sign out failed": "退出登录失败",
  "Sign out of Emdash?": "退出 Emdash？",
  "Uninstall skill?": "卸载技能？",
  "Uninstall failed": "卸载失败",
  "Install failed": "安装失败",
  "Device flow was canceled": "设备流程已取消",
  "Unable to remove GitHub account": "无法移除 GitHub 账户",
  "Unable to update default account": "无法更新默认账户",
  "Default GitHub account updated": "默认 GitHub 账户已更新",
  "GitHub account removed": "GitHub 账户已移除",
  "GitHub CLI accounts imported": "GitHub CLI 账户已导入",
  "Link GitHub account": "关联 GitHub 账户",
  "Sign in with GitHub": "使用 GitHub 登录",
  "Sign in to Emdash": "登录 Emdash",
  "Sign into your Emdash account": "登录您的 Emdash 账户",
  "Create or sign into your Emdash account with GitHub": "使用 GitHub 创建或登录 Emdash 账户",
  "Paste it in GitHub to authorize": "粘贴到 GitHub 以授权",
  "You will need to sign in again to reconnect your Emdash account.": "您需要重新登录以重新连接 Emdash 账户。",
  "Connected to GitHub": "已连接到 GitHub",
  "GitHub connection unsuccessful": "GitHub 连接失败",
  "Signed in to Emdash": "已登录 Emdash",
  "Add another GitHub account to your Emdash account": "添加另一个 GitHub 账户",
  "CLI Override": "CLI 覆盖",
  "Path Override": "路径覆盖",
  "Not installed": "未安装",
  "Installed": "已安装",

  // === Agent descriptions ===
  "CLI that connects to OpenAI models for project-aware code assistance and terminal workflows.": "连接 OpenAI 模型的 CLI，提供项目感知的代码辅助和终端工作流。",
  "CLI that uses Anthropic Claude for code edits, explanations, and structured refactors in the terminal.": "使用 Anthropic Claude 在终端中进行代码编辑、解释和结构化重构的 CLI。",
  "CLI that uses Google Gemini models to assist with coding, reasoning, and command-line tasks.": "使用 Google Gemini 模型辅助编码、推理和命令行任务的 CLI。",
  "Command-line interface to Alibaba": "阿里巴巴命令行接口工具",
};

// Merge: only add strings NOT already in dictionary
let added = 0;
let skipped = 0;
for (const [en, zh] of Object.entries(newTranslations)) {
  if (existing.has(en)) {
    skipped++;
    continue;
  }
  dict.exact[en] = zh;
  existing.add(en);
  added++;
}

writeFileSync(DICT_PATH, JSON.stringify(dict, null, 2) + '\n', 'utf-8');

console.log(`Added ${added} translations, skipped ${skipped} (already in dict).`);
console.log(`Total exact entries: ${Object.keys(dict.exact).length}`);
